library(shiny)
library(dplyr)

# --- Helpers ---
is_vowel <- function(letter) {
  tolower(letter) %in% c("a", "e", "i", "o", "u")
}

generate_distractor <- function(word) {
  letters_only <- unlist(strsplit(tolower(word), split = ""))
  vowels <- letters_only[sapply(letters_only, is_vowel)]
  consonants <- letters_only[!sapply(letters_only, is_vowel)]
  
  new_vowels <- sample(c("a", "e", "i", "o", "u"), length(vowels), replace = TRUE)
  new_consonants <- sample(setdiff(letters, c("a", "e", "i", "o", "u")), length(consonants), replace = TRUE)
  
  all_letters <- sample(c(new_vowels, new_consonants))
  paste(all_letters, collapse = "")
}

generate_side_triplets <- function(n_targets) {
  df <- as.data.frame(matrix(sample(c(0, 1), n_targets * 3, replace = TRUE), ncol = 3, byrow = TRUE))
  names(df) <- c("side1", "side2", "side3")
  return(df)
}

# --- UI ---
ui <- fluidPage(
  titlePanel("Repetion Maze Distractor Generator"),
  
  tags$head(
    tags$style(HTML("
      #add {background-color: #28a745; color: white;}
      #addSand {background-color: #007bff; color: white;}
      #delete {background-color: #dc3545; color: white;}
      #reset {background-color: #6c757d; color: white;}
      #prevTrial, #nextTrial {background-color: #fd7e14; color: white;}
      #downloadData {background-color: #556b2f; color: white; border: none;}
    "))
  ),
  
  sidebarLayout(
    sidebarPanel(
      textInput("sentence", "Enter a sentence:", "La mente deraglia per scelta"),
      actionButton("add", "Add Sentence"),
      actionButton("addSand", "Importa frasi SAND"),
      numericInput("deleteItem", "Delete item number:", NA),
      actionButton("delete", "Delete"),
      actionButton("reset", "Clear Dataset"),
      br(), br(),
      selectInput("distractorChoice", "Choose distractor version:", 
                  choices = c("dist1", "dist2", "dist3")),
      br(),
      downloadButton("downloadData", "Download Dataset"),
      br(), br(),
      actionLink("showInfo", "ℹ️ Info generation"),
      conditionalPanel(
        condition = "input.showInfo % 2 == 1",
        tags$hr(),
        h4("Distractor generation logic"),
        tags$p("For each target word, the distractor is generated by:"),
        tags$ul(
          tags$li("Counting the number of vowels and consonants in the target word."),
          tags$li("Sampling the same number of vowels (from a, e, i, o, u) and consonants (from all other letters), with replacement."),
          tags$li("Randomly shuffling all sampled letters to create a non-word distractor."),
          tags$li("This ensures phonological/orthographic balance without semantic interference.")
        ),
        tags$p("This process is automatic and unconstrained—manual checking is recommended to filter out real words or unintended similarities."),
        
        h4("Side assignment logic (left/right)"),
        tags$p("Each word receives 3 randomly generated side values (side1, side2, side3), one per distractor version."),
        tags$ul(
          tags$li("Each value is either 0 (target on right) or 1 (target on left), chosen with equal probability."),
          tags$li("The assigned side determines spatial layout in visual presentation."),
          tags$li("This supports counterbalanced lateralized stimulus presentation in line with visual search and psycholinguistic paradigms.")
        ),
        tags$p("You can select which distractor version (dist1, dist2, dist3) and its associated side to visualize in the interface."),
        tags$hr()
      )
    ),
    
    mainPanel(
      h4("Trial Presentation"),
      plotOutput("trialPlot", height = "200px"),
      fluidRow(
        column(6, align = "center", actionButton("prevTrial", "← Left")),
        column(6, align = "center", actionButton("nextTrial", "Right →"))
      ),
      hr(),
      h4("Dataset Preview"),
      tableOutput("outputTable")
    )
  )
)

# --- Server ---
server <- function(input, output, session) {
  dataset <- reactiveVal(data.frame())
  trialIndex <- reactiveVal(1)
  
  process_sentence <- function(sentence, item_id_start) {
    sentence <- gsub("['’]", "", sentence)
    words <- unlist(strsplit(sentence, "\\s+"))
    n_targets <- length(words)
    side_df <- generate_side_triplets(n_targets)
    
    rows <- bind_rows(lapply(seq_along(words), function(i) {
      data.frame(
        item = item_id_start,
        wp = i,
        target = words[i],
        dist1 = generate_distractor(words[i]),
        side1 = side_df$side1[i],
        dist2 = generate_distractor(words[i]),
        side2 = side_df$side2[i],
        dist3 = generate_distractor(words[i]),
        side3 = side_df$side3[i],
        stringsAsFactors = FALSE
      )
    }))
    return(rows)
  }
  
  observeEvent(input$add, {
    current_data <- dataset()
    new_item <- ifelse(nrow(current_data) == 0, 1, max(current_data$item) + 1)
    new_rows <- process_sentence(input$sentence, new_item)
    dataset(bind_rows(current_data, new_rows))
    trialIndex(1)
  })
  
  observeEvent(input$addSand, {
    sand_sentences <- c(
      "Il treno corre sui binari",
      "L’astronomo osserva le piante",
      "La bambina, che era sul prato, vide una farfalla posarsi su un albero",
      "Appena entrati nella stanza buia, abbiamo cercato l’interruttore per accendere la luce",
      "Il calciatore, che ha fatto un brutto fallo, è stato ammonito dall’arbitro",
      "Prima di mettere in moto la sua macchina, Luca si allacciò la scarpa"
    )
    
    current_data <- dataset()
    current_item <- ifelse(nrow(current_data) == 0, 1, max(current_data$item) + 1)
    
    new_data <- bind_rows(lapply(seq_along(sand_sentences), function(i) {
      process_sentence(sand_sentences[i], current_item + i - 1)
    }))
    
    dataset(bind_rows(current_data, new_data))
    trialIndex(1)
  })
  
  observeEvent(input$delete, {
    req(!is.na(input$deleteItem))
    dataset(dataset() %>% filter(item != input$deleteItem))
    trialIndex(1)
  })
  
  observeEvent(input$reset, {
    dataset(data.frame())
    trialIndex(1)
  })
  
  observeEvent(input$nextTrial, {
    idx <- trialIndex()
    if (idx < nrow(dataset())) {
      trialIndex(idx + 1)
    }
  })
  
  observeEvent(input$prevTrial, {
    idx <- trialIndex()
    if (idx > 1) {
      trialIndex(idx - 1)
    }
  })
  
  output$outputTable <- renderTable({
    dataset()
  })
  
  output$trialPlot <- renderPlot({
    data <- dataset()
    req(nrow(data) > 0)
    
    idx <- trialIndex()
    req(idx <= nrow(data))
    
    row <- data[idx, ]
    sideCol <- switch(input$distractorChoice,
                      "dist1" = row$side1,
                      "dist2" = row$side2,
                      "dist3" = row$side3)
    distCol <- row[[input$distractorChoice]]
    target <- row$target
    
    if (sideCol == 0) {
      left <- distCol
      right <- target
    } else {
      left <- target
      right <- distCol
    }
    
    par(mar = c(0, 0, 0, 0))
    plot(1, type = "n", xlim = c(0, 10), ylim = c(0, 1),
         xaxt = "n", yaxt = "n", bty = "n", xlab = "", ylab = "")
    text(3, 0.5, left, cex = 2)
    text(5, 0.5, "●", cex = 2)
    text(7, 0.5, right, cex = 2)
  })
  
  output$downloadData <- downloadHandler(
    filename = function() {
      paste0("stimuli_dataset_", Sys.Date(), ".csv")
    },
    content = function(file) {
      write.csv(dataset(), file, row.names = FALSE)
    }
  )
}

# --- Run app ---
shinyApp(ui = ui, server = server)
